export const country_to_code = {
	Afghanistan: 'AF',
	Albania: 'AL',
	Algeria: 'DZ',
	'American Samoa': 'AS',
	Andorra: 'AD',
	Angola: 'AO',
	Anguilla: 'AI',
	Antarctica: 'AQ',
	'Antigua and Barbuda': 'AG',
	Argentina: 'AR',
	Armenia: 'AM',
	Aruba: 'AW',
	Australia: 'AU',
	Austria: 'AT',
	Azerbaijan: 'AZ',
	Bahamas: 'BS',
	Bahrain: 'BH',
	Bangladesh: 'BD',
	Barbados: 'BB',
	Belarus: 'BY',
	Belgium: 'BE',
	Belize: 'BZ',
	Benin: 'BJ',
	Bermuda: 'BM',
	Bhutan: 'BT',
	Bolivia: 'BO',
	'Bosnia and Herzegovina': 'BA',
	Botswana: 'BW',
	'Bouvet Island': 'BV',
	Brazil: 'BR',
	'British Indian Ocean Territory': 'IO',
	'Brunei Darussalam': 'BN',
	Bulgaria: 'BG',
	'Burkina Faso': 'BF',
	Burundi: 'BI',
	Cambodia: 'KH',
	Cameroon: 'CM',
	Canada: 'CA',
	'Cape Verde': 'CV',
	'Cayman Islands': 'KY',
	'Central African Republic': 'CF',
	Chad: 'TD',
	Chile: 'CL',
	China: 'CN',
	'Christmas Island': 'CX',
	'Cocos (Keeling) Islands': 'CC',
	Colombia: 'CO',
	Comoros: 'KM',
	Congo: 'CG',
	'Congo, the Democratic Republic of the': 'CD',
	'Cook Islands': 'CK',
	'Costa Rica': 'CR',
	"Cote D'Ivoire": 'CI',
	Croatia: 'HR',
	Cuba: 'CU',
	Cyprus: 'CY',
	'Czech Republic': 'CZ',
	Denmark: 'DK',
	Djibouti: 'DJ',
	Dominica: 'DM',
	'Dominican Republic': 'DO',
	Ecuador: 'EC',
	Egypt: 'EG',
	'El Salvador': 'SV',
	'Equatorial Guinea': 'GQ',
	Eritrea: 'ER',
	Estonia: 'EE',
	Ethiopia: 'ET',
	'Falkland Islands (Malvinas)': 'FK',
	'Faroe Islands': 'FO',
	Fiji: 'FJ',
	Finland: 'FI',
	France: 'FR',
	'French Guiana': 'GF',
	'French Polynesia': 'PF',
	'French Southern Territories': 'TF',
	Gabon: 'GA',
	Gambia: 'GM',
	Georgia: 'GE',
	Germany: 'DE',
	Ghana: 'GH',
	Gibraltar: 'GI',
	Greece: 'GR',
	Greenland: 'GL',
	Grenada: 'GD',
	Guadeloupe: 'GP',
	Guam: 'GU',
	Guatemala: 'GT',
	Guinea: 'GN',
	'Guinea-Bissau': 'GW',
	Guyana: 'GY',
	Haiti: 'HT',
	'Heard Island and McDonald Islands': 'HM',
	'Holy See (Vatican City State)': 'VA',
	Honduras: 'HN',
	'Hong Kong': 'HK',
	Hungary: 'HU',
	Iceland: 'IS',
	India: 'IN',
	Indonesia: 'ID',
	'Iran, Islamic Republic of': 'IR',
	Iraq: 'IQ',
	Ireland: 'IE',
	Israel: 'IL',
	Italy: 'IT',
	Jamaica: 'JM',
	Japan: 'JP',
	Jordan: 'JO',
	Kazakhstan: 'KZ',
	Kenya: 'KE',
	Kiribati: 'KI',
	'North Korea': 'KP',
	'South Korea': 'KR',
	Kuwait: 'KW',
	Kyrgyzstan: 'KG',
	"Lao People's Democratic Republic": 'LA',
	Latvia: 'LV',
	Lebanon: 'LB',
	Lesotho: 'LS',
	Liberia: 'LR',
	Libya: 'LY',
	Liechtenstein: 'LI',
	Lithuania: 'LT',
	Luxembourg: 'LU',
	Macao: 'MO',
	Madagascar: 'MG',
	Malawi: 'MW',
	Malaysia: 'MY',
	Maldives: 'MV',
	Mali: 'ML',
	Malta: 'MT',
	'Marshall Islands': 'MH',
	Martinique: 'MQ',
	Mauritania: 'MR',
	Mauritius: 'MU',
	Mayotte: 'YT',
	Mexico: 'MX',
	'Micronesia, Federated States of': 'FM',
	'Moldova, Republic of': 'MD',
	Monaco: 'MC',
	Mongolia: 'MN',
	Montserrat: 'MS',
	Morocco: 'MA',
	Mozambique: 'MZ',
	Myanmar: 'MM',
	Namibia: 'NA',
	Nauru: 'NR',
	Nepal: 'NP',
	Netherlands: 'NL',
	'New Caledonia': 'NC',
	'New Zealand': 'NZ',
	Nicaragua: 'NI',
	Niger: 'NE',
	Nigeria: 'NG',
	Niue: 'NU',
	'Norfolk Island': 'NF',
	'North Macedonia, Republic of': 'MK',
	'Northern Mariana Islands': 'MP',
	Norway: 'NO',
	Oman: 'OM',
	Pakistan: 'PK',
	Palau: 'PW',
	'State of Palestine,Palestine': 'PS',
	Panama: 'PA',
	'Papua New Guinea': 'PG',
	Paraguay: 'PY',
	Peru: 'PE',
	Philippines: 'PH',
	Pitcairn: 'PN',
	Poland: 'PL',
	Portugal: 'PT',
	'Puerto Rico': 'PR',
	Qatar: 'QA',
	Reunion: 'RE',
	Romania: 'RO',
	'Russian Federation,Russia': 'RU',
	Rwanda: 'RW',
	'Saint Helena': 'SH',
	'Saint Kitts and Nevis': 'KN',
	'Saint Lucia': 'LC',
	'Saint Pierre and Miquelon': 'PM',
	'Saint Vincent and the Grenadines': 'VC',
	Samoa: 'WS',
	'San Marino': 'SM',
	'Sao Tome and Principe': 'ST',
	'Saudi Arabia': 'SA',
	Senegal: 'SN',
	Seychelles: 'SC',
	'Sierra Leone': 'SL',
	Singapore: 'SG',
	Slovakia: 'SK',
	Slovenia: 'SI',
	'Solomon Islands': 'SB',
	Somalia: 'SO',
	'South Africa': 'ZA',
	'South Georgia and the South Sandwich Islands': 'GS',
	Spain: 'ES',
	'Sri Lanka': 'LK',
	Sudan: 'SD',
	Suriname: 'SR',
	'Svalbard and Jan Mayen': 'SJ',
	Eswatini: 'SZ',
	Sweden: 'SE',
	Switzerland: 'CH',
	'Syrian Arab Republic': 'SY',
	'Taiwan, Province of China,Taiwan': 'TW',
	Tajikistan: 'TJ',
	'Tanzania, United Republic of': 'TZ',
	Thailand: 'TH',
	'Timor-Leste': 'TL',
	Togo: 'TG',
	Tokelau: 'TK',
	Tonga: 'TO',
	'Trinidad and Tobago': 'TT',
	Tunisia: 'TN',
	Turkey: 'TR',
	Turkmenistan: 'TM',
	'Turks and Caicos Islands': 'TC',
	Tuvalu: 'TV',
	Uganda: 'UG',
	Ukraine: 'UA',
	'United Arab Emirates': 'AE',
	'United Kingdom,UK,Great Britain': 'GB',
	'United States of America,USA': 'US',
	'United States Minor Outlying Islands': 'UM',
	Uruguay: 'UY',
	Uzbekistan: 'UZ',
	Vanuatu: 'VU',
	Venezuela: 'VE',
	Vietnam: 'VN',
	'Virgin Islands, British': 'VG',
	'Virgin Islands, U.S.': 'VI',
	'Wallis and Futuna': 'WF',
	'Western Sahara': 'EH',
	Yemen: 'YE',
	Zambia: 'ZM',
	Zimbabwe: 'ZW',
	'Åland Islands': 'AX',
	'Bonaire, Sint Eustatius and Saba': 'BQ',
	Curaçao: 'CW',
	Guernsey: 'GG',
	'Isle of Man': 'IM',
	Jersey: 'JE',
	Montenegro: 'ME',
	'Saint Barthélemy': 'BL',
	'Saint Martin (French part)': 'MF',
	Serbia: 'RS',
	'Sint Maarten (Dutch part)': 'SX',
	'South Sudan': 'SS',
	Kosovo: 'XK'
};

export const nationality_to_code = {
	Afghan: 'AF',
	Albanian: 'AL',
	Algerian: 'DZ',
	Andorran: 'AD',
	Angolan: 'AO',
	Antiguans: 'AG',
	Argentinean: 'AR',
	Armenian: 'AM',
	Australian: 'AU',
	Austrian: 'AT',
	Azerbaijani: 'AZ',
	Bahamian: 'BS',
	Bahraini: 'BH',
	Bangladeshi: 'BD',
	Barbadian: 'BB',
	Belarusian: 'BY',
	Belgian: 'BE',
	Belizean: 'BZ',
	Beninese: 'BJ',
	Bermuda: 'BM',
	Bhutanese: 'BT',
	Bolivian: 'BO',
	'Bosnian - Herzegovinian': 'BA',
	Batswana: 'BW',
	'Bouvet Island': 'BV',
	Brazilian: 'BR',
	'British Indian Ocean Territory': 'IO',
	Bruneian: 'BN',
	Bulgarian: 'BG',
	Burkinabe: 'BF',
	Burundian: 'BI',
	Cambodian: 'KH',
	Cameroonian: 'CM',
	Canadian: 'CA',
	'Cape Verdean': 'CV',
	'Cayman Islands': 'KY',
	'Central African': 'CF',
	Chadian: 'TD',
	Chilean: 'CL',
	Chinese: 'CN',
	'Christmas Island': 'CX',
	'Cocos (Keeling) Islands': 'CC',
	Colombian: 'CO',
	Comoran: 'KM',
	'Congolese (Republic of the Congo)': 'CG',
	'Congolese (Democratic Republic of the Congo)': 'CD',
	'Cook Islands': 'CK',
	'Costa Rican': 'CR',
	Ivorian: 'CI',
	Croatian: 'HR',
	Cuban: 'CU',
	Cypriot: 'CY',
	Czech: 'CZ',
	Danish: 'DK',
	Djibouti: 'DJ',
	'Dominican (Dominica)': 'DM',
	'Dominican (Dominican Republic)': 'DO',
	Ecuadorean: 'EC',
	Egyptian: 'EG',
	Salvadoran: 'SV',
	'Equatorial Guinean': 'GQ',
	Eritrean: 'ER',
	Estonian: 'EE',
	Ethiopian: 'ET',
	'Falkland Islands (Malvinas)': 'FK',
	'Faroe Islands': 'FO',
	Fijian: 'FJ',
	Finnish: 'FI',
	French: 'FR',
	'French (French Guiana)': 'GF',
	'French (French Polynesia)': 'PF',
	'French (French Southern Territories)': 'TF',
	Gabonese: 'GA',
	Gambian: 'GM',
	Georgian: 'GE',
	German: 'DE',
	Ghanaian: 'GH',
	Gibraltar: 'GI',
	Greek: 'GR',
	Greenland: 'GL',
	Grenadian: 'GD',
	Guadeloupe: 'GP',
	Guam: 'GU',
	Guatemalan: 'GT',
	Guinean: 'GN',
	'Guinea-Bissauan': 'GW',
	Guyanese: 'GY',
	Haitian: 'HT',
	'Heard Island and Mcdonald Islands': 'HM',
	'Holy See (Vatican City State)': 'VA',
	Honduran: 'HN',
	'Hong Kong': 'HK',
	Hungarian: 'HU',
	Icelandic: 'IS',
	Indian: 'IN',
	Indonesian: 'ID',
	Iranian: 'IR',
	Iraqi: 'IQ',
	Irish: 'IE',
	Israeli: 'IL',
	Italian: 'IT',
	Jamaican: 'JM',
	Japanese: 'JP',
	Jordanian: 'JO',
	Kazakhstani: 'KZ',
	Kenyan: 'KE',
	'I-Kiribati': 'KI',
	'North Korean': 'KP',
	'South Korean': 'KR',
	Kuwaiti: 'KW',
	Kyrgyz: 'KG',
	Laotian: 'LA',
	Latvian: 'LV',
	Lebanese: 'LB',
	Mosotho: 'LS',
	Liberian: 'LR',
	Libyan: 'LY',
	Liechtensteiner: 'LI',
	Lithuanian: 'LT',
	Luxembourger: 'LU',
	Macao: 'MO',
	Malagasy: 'MG',
	Malawian: 'MW',
	Malaysian: 'MY',
	Maldivan: 'MV',
	Malian: 'ML',
	Maltese: 'MT',
	Marshallese: 'MH',
	Martinique: 'MQ',
	Mauritanian: 'MR',
	Mauritian: 'MU',
	Mayotte: 'YT',
	Mexican: 'MX',
	Micronesian: 'FM',
	Moldovan: 'MD',
	Monacan: 'MC',
	Mongolian: 'MN',
	Montserrat: 'MS',
	Moroccan: 'MA',
	Mozambican: 'MZ',
	Burmese: 'MM',
	Namibian: 'NA',
	Nauruan: 'NR',
	Nepalese: 'NP',
	Dutch: 'NL',
	'New Caledonia': 'NC',
	'New Zealander': 'NZ',
	Nicaraguan: 'NI',
	Nigerien: 'NE',
	Nigerian: 'NG',
	Niue: 'NU',
	'Norfolk Island': 'NF',
	Macedonian: 'MK',
	'Northern Mariana Islands': 'MP',
	Norwegian: 'NO',
	Omani: 'OM',
	Pakistani: 'PK',
	Palauan: 'PW',
	'Palestinian Territory, Occupied': 'PS',
	Panamanian: 'PA',
	'Papua New Guinea': 'PG',
	Paraguayan: 'PY',
	Peruvian: 'PE',
	Filipino: 'PH',
	Pitcairn: 'PN',
	Polish: 'PL',
	Portuguese: 'PT',
	'Puerto Rico': 'PR',
	Qatari: 'QA',
	Reunion: 'RE',
	Romanian: 'RO',
	Russian: 'RU',
	Rwandan: 'RW',
	'Saint Helena': 'SH',
	'Kittian and Nevisian': 'KN',
	'Saint Lucian': 'LC',
	'Saint Pierre and Miquelon': 'PM',
	'Saint Vincent and the Grenadines': 'VC',
	Samoan: 'WS',
	'San Marinese': 'SM',
	'Sao Tomean': 'ST',
	Saudi: 'SA',
	Senegalese: 'SN',
	Seychellois: 'SC',
	'Sierra Leonean': 'SL',
	Singaporean: 'SG',
	Slovakian: 'SK',
	Slovenian: 'SI',
	'Solomon Islander': 'SB',
	Somali: 'SO',
	'South African': 'ZA',
	'South Georgia and the South Sandwich Islands': 'GS',
	Spanish: 'ES',
	'Sri Lankan': 'LK',
	Sudanese: 'SD',
	Surinamer: 'SR',
	'Svalbard and Jan Mayen': 'SJ',
	Swazi: 'SZ',
	Swedish: 'SE',
	Swiss: 'CH',
	Syrian: 'SY',
	Taiwanese: 'TW',
	Tajik: 'TJ',
	Tanzanian: 'TZ',
	Thai: 'TH',
	'East Timorese': 'TL',
	Togolese: 'TG',
	Tokelau: 'TK',
	Tongan: 'TO',
	'Trinidadian or Tobagonian': 'TT',
	Tunisian: 'TN',
	Turkish: 'TR',
	Turkmenistan: 'TM',
	'Turks and Caicos Islands': 'TC',
	Tuvaluan: 'TV',
	Ugandan: 'UG',
	Ukrainian: 'UA',
	Emirian: 'AE',
	British: 'GB',
	American: 'US',
	'United States Minor Outlying Islands': 'UM',
	Uruguayan: 'UY',
	Uzbekistani: 'UZ',
	Vanuatu: 'VU',
	Venezuelan: 'VE',
	Vietnamese: 'VN',
	'Virgin Islands, British': 'VG',
	'Virgin Islands, U.S.': 'VI',
	Welsh: 'WF',
	'Western Sahara': 'EH',
	Yemenite: 'YE',
	Zambian: 'ZM',
	Zimbabwean: 'ZW',
	'Åland Islands': 'AX',
	'Bonaire, Sint Eustatius and Saba': 'BQ',
	Curaçao: 'CW',
	Guernsey: 'GG',
	Manx: 'IM',
	Jersey: 'JE',
	Montenegrin: 'ME',
	'Saint Barthélemy': 'BL',
	'Saint Martin (French part)': 'MF',
	Serbian: 'RS',
	'Sint Maarten (Dutch part)': 'SX',
	'South Sudan': 'SS',
	Kosovo: 'XK'
};
